// Auto-generated by npm run photos. Edit files in public/img/photos/* instead.
export type PhotoItem = {
  src: string;
  alt: string;
};

export type PhotoSection = {
  id: "favorites" | "travel" | "hobbies";
  title: string;
  sidebarLabel: string;
  photos: PhotoItem[];
};

export const photoSections: PhotoSection[] = [
  {
    "id": "favorites",
    "title": "Favorites",
    "sidebarLabel": "Favorites",
    "photos": [
      {
        "src": "img/photos/favorites/E8CAB601-5CF5-4A43-9DB1-12AD77341F4F.jpg",
        "alt": "E8CAB601 5CF5 4A43 9DB1 12AD77341F4F"
      },
      {
        "src": "img/photos/favorites/IMG_5369.JPG",
        "alt": "IMG 5369"
      },
      {
        "src": "img/photos/favorites/IMG_5881.jpg",
        "alt": "IMG 5881"
      },
      {
        "src": "img/photos/favorites/IMG_6044.JPG",
        "alt": "IMG 6044"
      },
      {
        "src": "img/photos/favorites/IMG_6577.JPG",
        "alt": "IMG 6577"
      },
      {
        "src": "img/photos/favorites/IMG_6654.JPG",
        "alt": "IMG 6654"
      },
      {
        "src": "img/photos/favorites/IMG_6798.JPG",
        "alt": "IMG 6798"
      }
    ]
  },
  {
    "id": "travel",
    "title": "Travel",
    "sidebarLabel": "Travel",
    "photos": [
      {
        "src": "img/photos/travel/6A4C7D40-73E2-4F56-BF13-F89DE47AD41C.JPG",
        "alt": "6A4C7D40 73E2 4F56 BF13 F89DE47AD41C"
      },
      {
        "src": "img/photos/travel/6C6603EE-51A3-4AE9-85EC-0CD7631E468F.JPG",
        "alt": "6C6603EE 51A3 4AE9 85EC 0CD7631E468F"
      },
      {
        "src": "img/photos/travel/35BCFA5A-F806-400B-B0CA-422F6ED65033.JPG",
        "alt": "35BCFA5A F806 400B B0CA 422F6ED65033"
      },
      {
        "src": "img/photos/travel/39CCF3AD-6D7F-4246-81B9-8468F1CB3C05.JPG",
        "alt": "39CCF3AD 6D7F 4246 81B9 8468F1CB3C05"
      },
      {
        "src": "img/photos/travel/59E18F37-1B21-4C26-8C40-0FC7347E68BC.JPG",
        "alt": "59E18F37 1B21 4C26 8C40 0FC7347E68BC"
      },
      {
        "src": "img/photos/travel/202ED6D4-27BC-48DF-80D0-B2D1C9EF6179.JPG",
        "alt": "202ED6D4 27BC 48DF 80D0 B2D1C9EF6179"
      },
      {
        "src": "img/photos/travel/9342A2C4-2312-4D89-B6A8-9106C6A7DA02.JPG",
        "alt": "9342A2C4 2312 4D89 B6A8 9106C6A7DA02"
      },
      {
        "src": "img/photos/travel/46534503-E67F-47EC-A0BC-78DAF022ECCF.JPG",
        "alt": "46534503 E67F 47EC A0BC 78DAF022ECCF"
      },
      {
        "src": "img/photos/travel/B967DF99-65CA-4C54-8509-237C297297A3.JPG",
        "alt": "B967DF99 65CA 4C54 8509 237C297297A3"
      },
      {
        "src": "img/photos/travel/EE76886D-223E-4F83-8F22-7B8FCE387433.JPG",
        "alt": "EE76886D 223E 4F83 8F22 7B8FCE387433"
      }
    ]
  },
  {
    "id": "hobbies",
    "title": "Hobbies",
    "sidebarLabel": "Hobbies",
    "photos": [
      {
        "src": "img/photos/hobbies/IMG_5172.JPG",
        "alt": "IMG 5172"
      },
      {
        "src": "img/photos/hobbies/IMG_6027.JPG",
        "alt": "IMG 6027"
      },
      {
        "src": "img/photos/hobbies/IMG_6057.JPG",
        "alt": "IMG 6057"
      },
      {
        "src": "img/photos/hobbies/IMG_9035.jpg",
        "alt": "IMG 9035"
      }
    ]
  }
];
